### ISSUE TITLE
Doesn't work in Sketch 50

### ISSUE THREAD

**Issue by wrybit** [zeroheight/library-symbol-replacer#11]
Hi,

seems like it doesn't work in Sketch 50 ... :(
The Replacement gets started, but don't show the end dialog and no Sym. gets replaced.

Greez Jens

**Comment by ahujasid** [comment]
Yep, same exact problem for me as well. It identifies the symbols and instances but on clicking Import nothing happens.

**Comment by robintindale** [comment]
Taking a look 👀

**Comment by robintindale** [comment]
Give version `1.0.16` a go 👍

**Comment by calderaricaio** [comment]
It's fixed here with the new version!

**Comment by robintindale** [comment]
great :)
