### ISSUE TITLE
Plugin not preserving overrides

### ISSUE THREAD

**Issue by dave-hawkins** [zeroheight/library-symbol-replacer#2]
Hey, would love to use this plugin but getting a bit of an issue. 

Can you offer any better insight into why if my symbols are both named the exact same thing, the overrides are not being preserved?

It finds the two instances I have, overwrites the symbol, but doesn't preserve my overrides in the process.

Will happily provide source files if that helps.

**Comment by dave-hawkins** [comment]
Just a bit of further testing:

Abstracting the symbols to a new sketch document and then running the plugin makes it work, but pasting the newly Library-d symbols back into my working document reverts them back to the un-libraried one. 🙈

**Comment by robintindale** [comment]
erf - sorry Sketch symbols are very temperamental 😢  Yes source files are always helpful :) I have a few test cases already, so that might be enough already when I get time to bash my head against them

**Comment by dave-hawkins** [comment]
Certainly not your fault.. seems a big oversight on sketch's point of view not to offer this ability natively. I managed to fix it finally by abstracting them into a new document then bringing them over in batches, but nothing seemed to work when i tried the whole doc.. feel free to close this issue for now and thanks for the hard work as you definitely saved me a few hours :)
