### ISSUE TITLE
Remember last used Libary

### ISSUE THREAD

**Issue by patrickplaggenborg** [zeroheight/library-symbol-replacer#3]
Love this plugin. Use it a lot.

Right now, every time when I run it, it asks me to select the Sketch library file and opens a Finder Browse window in my Mac user home folder.

Takes quite some clicks/key presses to find it.

Current workaround to speed up workflow:
- Put the Sketch library location or file itself in the Finder favourites sidebar 

A plugin enhancement would be preferred:
- remember the Last Used Library for every next time you run the plugin
- add 'Change Library' if you want to sync from another library

Or, maybe easier and still very helpful:
- remember last used file or last used 'enclosing folder' in Finder Browse window
Or, if that's impossible:
- open enclosing folder of current open Sketch file in Finder Browse window

**Comment by robintindale** [comment]
added in 1.0.11
![image](https://user-images.githubusercontent.com/2700528/32114798-51f8c708-bb3c-11e7-88b0-5067730f611a.png)

if there is no previous library, will be prompted to choose one
