### ISSUE TITLE
Don't accept my file since today

### ISSUE THREAD

**Issue by ekiwnox** [zeroheight/library-symbol-replacer#4]
Hi guy,

Hope you're all doing well !
I get a weird problem with the plugin today, I cannot select the library file to replace all the symbols like previously. I get this message : **Sorry, that file is not a Library. Add it as a Library and try again**.

It works perfectly yesterday with the same file. I've uninstalled the plugin and reinstalled it but nothing work :-/. Someone can help me ?

**Comment by ekiwnox** [comment]
I solved my problem ! I delete my file from the library and relinked it as a library. 
It works now :-)

**Comment by robintindale** [comment]
Great 😄  As a guess, maybe the file moved on your filesystem - so Sketch no longer thought of it as a library
