### ISSUE TITLE
Nested symbols in different libraries

### ISSUE THREAD

**Issue by drasnop** [zeroheight/library-symbol-replacer#5]
If you have nested symbols that you want to send to different libraries (e.g. components that contain icons, and you want a separate Components and Icons library), it might be worth pointing out that the process outlined in the [Readme](https://github.com/zeroheight/library-symbol-replacer#breaking-up-a-big-file) wouldn't quite work. When you copy your components symbols out of your original file, you'll bring with them the icon symbols that they contain, which would create duplicates (the same icon would become two symbols, one in Components and one in Icons).

To remedy that you can either:

- Run the replacer plugin within your Components library first, to replace all icon symbols by icons from the Icons library. You should make sure that Components doesn't contain any other symbols than the component ones. Then you can run the plugin within your original file.
- Or: run the replacer plugin in your original file *after* transferring out the icons, but *before* transferring out the components themselves. That way the components will already be linked with the Icons Library's icons, instead of the local ones. If you have circular dependencies between your libraries, this approach might not be feasible.

I believe the overrides will be preserved with either method; but who can claim to know the mysteries of Sketch?

**Comment by robintindale** [comment]
yeah hopefully this will be slightly improved with Sketch 48, where they fixed the issue with copy-paste symbols not staying pointing to their library.

I've added your comments to the `README.md` and credited you 👍
