### ISSUE TITLE
Replacing library symbols (not just document symbols)

### ISSUE THREAD

**Issue by timohofmeijer** [zeroheight/library-symbol-replacer#7]
Hi, I’m wondering what the additional effort would be to be able to also replace library symbols, not just document symbols.

I’m trying to import an existing Sketch Library together with some Sketch document using this Library. Making the symbol instances point to the Abstract version of this Library is not working out for me..

**Comment by robintindale** [comment]
Could you explain a bit more in detail what you want to replace? I'm not quite understanding, sorry!

**Comment by timohofmeijer** [comment]
What I want to do is replace library symbols with the symbols from another library (but with the same name). This problem is quite specific to importing an existing Library setup into Abstract I think. Abstract doesn’t link up the imported design documents with the imported library.

I solved it by using the `Organize imported Symbols...` to unlink the symbols from the deprecated Library followed by using your plugin to replace the Symbols with the Abstract library symbols.




does not keep te
