### ISSUE TITLE
MSLayerPaster.updateOverridesOnInstance_withIDMap_ is not a function

### ISSUE THREAD

**Issue by sonburn** [zeroheight/library-symbol-replacer#8]
@robintindale, just a heads up, you and I both share this bug when trying to update overrides...

"MSLayerPaster.updateOverridesOnInstance_withIDMap_ is not a function"

It looks like the folks at Bohemian changed a lot with MSLayerPaster, and I am just now noticing this bug in Symbol Swapper...

Sketch 47
https://github.com/abynim/Sketch-Headers/blob/cea339410eeb1590edf53ee127c5dd507abd1b73/Headers/MSLayerPaster.h

Sketch 48
https://github.com/abynim/Sketch-Headers/blob/master/Headers/MSLayerPaster.h

**Comment by sonburn** [comment]
Looks like the functionality has been moved to MSSymbolInstance...

https://github.com/abynim/Sketch-Headers/blob/master/Headers/MSSymbolInstance.h

**Comment by robintindale** [comment]
I fixed this with https://github.com/zeroheight/library-symbol-replacer/commit/6d6ba0a434664314023d5d92d44f15ae687b742a and https://github.com/zeroheight/library-symbol-replacer/commit/13652655328f2897b879b1b5ea765581e35231a0 I believe. Are you seeing buggy behavior?

**Comment by sonburn** [comment]
My bad, I didn’t think to check my version. Apologies for the false alarm.

**Comment by robintindale** [comment]
No worries :)
