### ISSUE TITLE
Can't replace symbols that are already linked to an old library file

### ISSUE THREAD

**Issue by hikarusalmat** [zeroheight/library-symbol-replacer#9]
I have a baseline sketch file setup that consists of a library file and multiple page files that are linked to the library file. For a new project I'd duplicate the set and relink the duplicated page files to the duplicated library file.

Would be great if this plugin can support this scenario, and have option to replace absolutely all symbols (including symbols that are linked to old/another library).

**Comment by robintindale** [comment]
Symbol swapper (https://github.com/sonburn/symbol-swapper) just added a feature which may help with this
<img src='https://raw.githubusercontent.com/sonburn/symbol-swapper/master/Screenshots/Library%20Swapper.png'>

**Comment by hikarusalmat** [comment]
@robintindale Thank you for letting me know about this, it works like a charm!
